name: Build and Deploy
on: [push]

jobs:
  build:
    name: Build & Push Container
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: |
            docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Docker Build
        run: |
            docker build -t ramona .
      - name: Docker Push
        run: |
            docker tag ramona docker.pkg.github.com/kryptn/ramona/ramona:latest
            docker tag ramona docker.pkg.github.com/kryptn/ramona/ramona:$GITHUB_SHA
            docker push docker.pkg.github.com/kryptn/ramona/ramona:latest
            docker push docker.pkg.github.com/kryptn/ramona/ramona:$GITHUB_SHA