name: Build and Deploy
on: [push]

jobs:
  build:
    name: Build & Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Terraform
        env:
            TERRAFORM_VERSION: "0.12.15"
        run: |
            tf_version=$TERRAFORM_VERSION
            wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
            unzip terraform_"$tf_version"_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
      - name: Terraform Init
        env:
            TF_API_TOKEN: ${{ secrets.TF_API_TOKEN}}
        run: |
            cd infra/
            terraform init -backend-config="token=$TF_API_TOKEN"
            cd ..
      - name: Docker Login
        run: |
            docker login -u kryptn -p {{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Docker Build
        run: |
            docker build -t docker.pkg.github.com/kryptn/ramona/ramona:latest .
      - name: Docker Push
        run: |
            docker push docker.pkg.github.com/kryptn/ramona/ramona:latest
