name: Build and Deploy
on: [push]

jobs:
  build:
    name: Build & Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: |
            docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
      - name: Docker Build
        run: |
            docker build -t docker.pkg.github.com/kryptn/ramona/ramona:latest .
      - name: Docker Push
        run: |
            docker push docker.pkg.github.com/kryptn/ramona/ramona:latest